/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface RaceResult {
        "match": MatchResults;
    }
    interface ResultTableComponent {
        /**
          * Data for the whole row
         */
        "data": any;
        /**
          * Name of the field for the column
         */
        "field": string;
        /**
          * The value to display in the table cell
         */
        "value": any;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLRaceResultElement extends Components.RaceResult, HTMLStencilElement {
    }
    var HTMLRaceResultElement: {
        prototype: HTMLRaceResultElement;
        new (): HTMLRaceResultElement;
    };
    interface HTMLResultTableComponentElement extends Components.ResultTableComponent, HTMLStencilElement {
    }
    var HTMLResultTableComponentElement: {
        prototype: HTMLResultTableComponentElement;
        new (): HTMLResultTableComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "race-result": HTMLRaceResultElement;
        "result-table-component": HTMLResultTableComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface RaceResult {
        "match"?: MatchResults;
    }
    interface ResultTableComponent {
        /**
          * Data for the whole row
         */
        "data"?: any;
        /**
          * Name of the field for the column
         */
        "field"?: string;
        /**
          * The value to display in the table cell
         */
        "value"?: any;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "race-result": RaceResult;
        "result-table-component": ResultTableComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "race-result": LocalJSX.RaceResult & JSXBase.HTMLAttributes<HTMLRaceResultElement>;
            "result-table-component": LocalJSX.ResultTableComponent & JSXBase.HTMLAttributes<HTMLResultTableComponentElement>;
        }
    }
}
